sudo: required
language: cpp
services:
- docker
notifications:
  email: false
  slack:
    secure: gbC/4OXc8gvzHeqYcaHKhtq5AJUgD9YZsdp8ArxvTH0MizdjU1WTDDn7VvRPVJEwJECeldRadK9MzXrYMSOhy5pLL3Oj2ITpwmeYGK0rQEADGNacRloQpLNlrAyI+rlRXciLGvnUDdd4RNLh8Sf89606Vrw/vsGtO9HfQYYN/mDqlXEaucD2nAe3/FUsqfZGwpnNlgjteXVqTWaMWzxif4BlaBnVTFKrL0+dMN4esuvH96b6cgLp/ejgR+VmR09JYia7WQPlGm5Ck0SNGbO80cyoiYuOUgNAKVi65Zg9+kHIVXHDG2K4wxUyk3kTbPK2NR62I/jOcykraTEAh5PqdTx4I5UuYJtd8orjh3vPo8hzqGXXXdd31k1cjHpHN0Y4BDXUOXdqaRyZHrFH+zpe7ty8y4Ywq3Q0/5I6dZvJAphyz200xxtc9d6S2PPvLQkoUjpJFg4OM6c1B0trGAr2RjfoAVxPJQk/t+jzrC0ln7sLeegkR9kcLEhz/2QyxrWEomzlCoQorunki/414WczqrpGw9UQ/k9zxuCd0vCZicRatd1vzS7MQ10kGZoZCmsp+hxp9Qolz2PIN+cGKhrXCEZMcEtDtZgmDN7D9XTUV6WWqTzK3evWidempWiyetJ6z5cAg1u3YbJKgU9V3FQsY4Im3HQ5xYSR3tbxpo4L798=
install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update
- sudo apt-get install -y gcc-5 g++-5 -y && CC=gcc-5 && CXX=g++-5
- sudo apt-get install -y libzmq3-dev
- git clone --branch v1.9.0 https://github.com/google/flatbuffers.git && cd flatbuffers
  && cmake -G "Unix Makefiles" && sudo make install && cd ..
- git clone --branch 0.4.0 https://github.com/QuantStack/xtl.git && cd xtl && cmake
  . && sudo make install && cd ..
- git clone --branch 0.15.4 https://github.com/QuantStack/xtensor.git && cd xtensor
  && cmake . && sudo make install && cd ..
script:
- mkdir build && cd build
- cmake ../src
- cmake --build .
- sudo make install
- cd ..
after_success:
- export CURRENT_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH;
  else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, TRAVIS_TAG=$TRAVIS_TAG, CURRENT_BRANCH=$CURRENT_BRANCH"
- if [[ "$CURRENT_BRANCH" == "master" ]] || [[ -n "$TRAVIS_TAG" ]]; then GIT_COMMIT="$(git
  rev-parse HEAD)" ; echo $GIT_COMMIT ; docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  ; docker build -t probprog/pyprob_cpp --build-arg GIT_COMMIT=$GIT_COMMIT . ; docker
  tag probprog/pyprob_cpp probprog/pyprob_cpp:latest ; docker push probprog/pyprob_cpp:latest
  ; if [[ -n "$TRAVIS_TAG" ]]; then docker tag probprog/pyprob_cpp probprog/pyprob_cpp:$TRAVIS_TAG
  ; docker push probprog/pyprob_cpp:$TRAVIS_TAG ; fi fi
